#define WARNING_EXAMPLE "This is a warning example"
#define ERROR_EXAMPLE "This is a error example"
#define DEBUG_EXAMPLE "This is a debug example"

#define INVALID_ARGS_NUM "Invalid number of arguments" 
#define FILE_OPEN "Can't open file:" 
#define ALLOCATION_ERROR "Allocation failure" 
#define PRINT_SYM_TABLE "Printing the symbol table:"
#define ALREADY_INITIALIZED_LABEL "Label already initialized"
#define CANT_ADD_TO_SYMTABLE "Can't add label to symbol table"
#define INVALID_INSTRUCTION "Invalid instruction"
#define INVALID_LABEL_DIRECTIVE "Invalid label directive"
#define CANT_ADD_TO_DATA_IMAGE "Can't add a new image entry into data image"
#define TEXT_AFTER_END_OF_STR_NOT_RELEVANT "The text after the second double quote will note be taken into consideration"
#define CANT_FIND_STRING "Unable to find the begining or end of the string"
#define INVALID_LIST_DATA "Invalid list of data"
#define INVALID_LABEL_NAME "Invalid label name"
